### ISSUE TITLE
Metaballs display type

### ISSUE THREAD

**Issue by blairlyons** [simularium/simulariumio#96]
## Use Case
As a user with agents that change shape over time, I want to prepare my data to visualize these agents without having to prepare meshes for each agent at each time step.

## Acceptance Criteria
Simularium files have a metaballs display type, where positions and radii of metaballs are saved in subpoints for that agent.

## Details
- add a display type "METABALLS"
- save XYZ position and radius for each metaball in the subpoints for the agent, i.e. [metaball1 position X, metaball1 position Y, metaball1 position Z, metaball1 radius, metaball2 position X, metaball2 position Y, metaball2 position Z, metaball2 radius, ...]
- also add a viz type "METABALLS"? Or is now a good time to talk about removing viz type since it is redundant with display type?

**Comment by blairlyons** [comment]
@toloudis does this sound right? and what do you think about the viz type vs display type issue?

**Comment by toloudis** [comment]
At first glance, I'd say we don't want to add more vis types.  We want to phase that out (e.g. leave it there but never depend on it) and have the display driven by the agent type's display info.  

The deeper implication is the following:  if a single agent needs to change its display type, how do we handle it?   I could imagine possibly letting an agent type description having several displaytypes to choose from.  Instead of just saying {displayType:"SPHERE"}, you could have a list [{displayType:"SPHERE"}, {displayType:"OBJ", url:"meshurl"}] and NOW a single particular agent of this type could have a bit of info that lets it flipflop between sphere and obj (the per-agent vistype is now 0 or 1 to select from its agent type's display options).

I would suggest that we prototype the metaballs by generating an all-subpoints version of one of the ABM files, to at least demonstrate converting subpoints to metaball.

**Comment by toloudis** [comment]
I'll show you my implementation in a PR for the viewer and you'll see the display type I created.

**Comment by toloudis** [comment]
https://github.com/simularium/simularium-viewer/pull/261/files#diff-94ea671de54a9e3dcdb0381fad89b6322ec71f112081552ebca4369d9b60f597R9
